
export let SCREENS = {
  ONBOARDING: 'Onboarding',
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  PROGRESS: 'Progress',
  VERIFYCODE: 'VerifyCode',
  FORGET: 'Forget',
  RESETPASSWORD: 'ResetPassword',
  HOME: 'Home',
  FILTERS: 'Filters',
  MESSAGES: 'Messages',
  BOOKING: 'Booking',
  SEEALL: 'SeeALL',
  DETAILS: 'Details',
  PROFILE: 'Profile',
  TERMSANDCONDITION: 'TermsAndCondition',
  DASHBOARD: 'dashboard',
  TABS: 'Tabs',
  SEEALLDOCTORS: 'SeeAllDoctors',
  // DOCTORDETAILS: 'DoctorDetails',
  NEWAPPOINTMENT: 'NewAppointment',
  NOTIFICATONS: 'Notifications',
  CHAT: 'Chat',
  UPDATEPROFILE: 'UpdateProfile',
  FAVORITES: 'Favorites',
  HELPCENTER: 'HelpCenter',
  PAYMENTOPTION: 'PaymentOption',
  PASSWORDMANAGER: 'PasswordManager',
  NOTIFICATIONSETTINGS: 'NotificationsSettings',
  THEMESETTINGS: 'ThemeSettings',
  MYAPPOINTMENT: 'MyAppointment',
  CANCELAPPOINTMENT: 'CancelAppointment',
  ADDCARD: 'AddCard',
  REVIEWSUMMARY: 'ReviewSummary',
  PAYMENTSUCCESS: 'PaymentSuccess',
  CALL: 'CallScreen',
  CALL_HISTORY: 'CallHistory',

  // Doctor Module Screens
  DOCTOR_DASHBOARD: 'DoctorDashboard',
  DOCTOR_PROFILE: 'DoctorProfile',
  DOCTOR_PATIENTS: 'DoctorPatients',
  PATIENT_PROFILE: 'PatientProfile',
  CONSULTATION_NOTES: 'ConsultationNotes',
  MANAGE_AVAILABILITY: 'ManageAvailability',
  DOCTOR_EARNINGS: 'DoctorEarnings',
  DOCTOR_APPOINTMENTS: 'DoctorAppointments',
};